//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.24 at 09:06:31 AM CEST 
//


package com.trivadis.integrationws.visacard.schemas;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="cardNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="cardholderFirstName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="cardholderLastName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="validThroughMonth" type="{http://trivadis.com/integrationws/visaCard/schemas}ValidThroughMonthT"/>
 *         &lt;element name="validThroughYear" type="{http://trivadis.com/integrationws/visaCard/schemas}ValidThroughYearT"/>
 *         &lt;element name="bookAmount" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "cardNumber",
    "cardholderFirstName",
    "cardholderLastName",
    "validThroughMonth",
    "validThroughYear",
    "bookAmount"
})
@XmlRootElement(name = "BookRequest")
public class BookRequest {

    @XmlElement(required = true)
    protected String cardNumber;
    @XmlElement(required = true)
    protected String cardholderFirstName;
    @XmlElement(required = true)
    protected String cardholderLastName;
    @XmlElement(required = true)
    protected String validThroughMonth;
    @XmlElement(required = true)
    protected String validThroughYear;
    protected double bookAmount;

    /**
     * Gets the value of the cardNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCardNumber() {
        return cardNumber;
    }

    /**
     * Sets the value of the cardNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCardNumber(String value) {
        this.cardNumber = value;
    }

    /**
     * Gets the value of the cardholderFirstName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCardholderFirstName() {
        return cardholderFirstName;
    }

    /**
     * Sets the value of the cardholderFirstName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCardholderFirstName(String value) {
        this.cardholderFirstName = value;
    }

    /**
     * Gets the value of the cardholderLastName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCardholderLastName() {
        return cardholderLastName;
    }

    /**
     * Sets the value of the cardholderLastName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCardholderLastName(String value) {
        this.cardholderLastName = value;
    }

    /**
     * Gets the value of the validThroughMonth property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValidThroughMonth() {
        return validThroughMonth;
    }

    /**
     * Sets the value of the validThroughMonth property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValidThroughMonth(String value) {
        this.validThroughMonth = value;
    }

    /**
     * Gets the value of the validThroughYear property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValidThroughYear() {
        return validThroughYear;
    }

    /**
     * Sets the value of the validThroughYear property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValidThroughYear(String value) {
        this.validThroughYear = value;
    }

    /**
     * Gets the value of the bookAmount property.
     * 
     */
    public double getBookAmount() {
        return bookAmount;
    }

    /**
     * Sets the value of the bookAmount property.
     * 
     */
    public void setBookAmount(double value) {
        this.bookAmount = value;
    }

}
